In [1]:
from models.hybrid.recommender import LightFMRecommender
from lightfm import LightFM
import pickle
import pickle5
import pandas as pd
from lightfm.cross_validation import random_train_test_split
from lightfm.data import Dataset
from lightfm.evaluation import auc_score, precision_at_k, recall_at_k

C:\Users\Asus ROG\Anaconda3\lib\site-packages\lightfm\_lightfm_fast.py:9: UserWarning: LightFM was compiled without OpenMP support. Only a single thread will be used.
  warnings.warn('LightFM was compiled without OpenMP support. '
Using TensorFlow backend.


In [2]:
# model = pickle5.load(open("models/hybrid/hybrid_model_popular_active.pickle", 'rb'))


self = LightFMRecommender()

data = self._filter_data
dataset = Dataset()

dataset.fit(data['Cust_Id'].unique(), data['Movie_Id'].unique(), item_features=self.get_combination)
(interactions, weights) = dataset.build_interactions([(x['Cust_Id'],
                                                             x['Movie_Id'],
                                                             x['Rating']) for index, x in data.iterrows()])

movies_id, tfidf_data = self.get_tfidf_matrix
features_lists = [list(x) for x in tfidf_data.values]
movies_features = dataset.build_item_features(data=self.get_movies_tuple(features_lists, movies_id, tfidf_data))

In [36]:
[x for x in features_lists[3] if x != float(0)]

[0.5773502691896257, 0.5773502691896257, 0.5773502691896257]

In [44]:
x = self.get_movies_tuple(features_lists, movies_id, tfidf_data)

In [51]:
x[100]

(900,
 ['academy:0.0',
  'according:0.0',
  'ace:0.0',
  'act:0.0',
  'action:0.0',
  'addams:0.0',
  'ado:0.0',
  'adventure:0.0',
  'adventures:0.0',
  'affair:0.0',
  'afraid:0.0',
  'afternoon:0.0',
  'agent:0.0',
  'ai:0.0',
  'air:0.0',
  'airplane:0.0',
  'alabama:0.0',
  'aladdin:0.0',
  'alexander:0.0',
  'alien:0.0',
  'aliens:0.0',
  'alone:0.0',
  'along:0.0',
  'altar:0.0',
  'amaro:0.0',
  'amazing:0.0',
  'america:0.0',
  'american:0.0',
  'anacondas:0.0',
  'anchorman:0.0',
  'angels:0.0',
  'angry:0.0',
  'animal:0.0',
  'annie:0.0',
  'anniversary:0.0',
  'another:0.0',
  'anymore:0.0',
  'apocalypse:0.0',
  'aquatic:0.0',
  'ark:0.0',
  'armed:0.0',
  'around:0.0',
  'arrested:0.0',
  'arsenic:0.0',
  'artificial:0.0',
  'atlantis:0.0',
  'attack:0.0',
  'austin:0.0',
  'autumn:0.0',
  'away:0.0',
  'axe:0.0',
  'azkaban:0.0',
  'baby:0.0',
  'babysitters:0.0',
  'back:0.0',
  'bad:0.0',
  'bagger:0.0',
  'bambi:0.0',
  'bang:0.0',
  'banks:0.0',
  'barbershop:0.0',


## EDA

In [ ]:
train, test = random_train_test_split(interactions, test_percentage=0.4,
                                              random_state=np.random.RandomState(7))

In [16]:
data.shape

(335679, 3)

In [13]:
interactions.todense()

matrix([[1, 1, 1, ..., 1, 1, 1],
        [1, 1, 1, ..., 1, 1, 1],
        [1, 0, 1, ..., 1, 1, 1],
        ...,
        [0, 0, 0, ..., 0, 1, 1],
        [0, 0, 0, ..., 0, 0, 1],
        [0, 0, 0, ..., 1, 0, 1]])

In [12]:
weights.todense()

matrix([[1., 2., 3., ..., 2., 2., 4.],
        [3., 4., 4., ..., 5., 4., 5.],
        [2., 0., 3., ..., 3., 2., 4.],
        ...,
        [0., 0., 0., ..., 0., 4., 4.],
        [0., 0., 0., ..., 0., 0., 3.],
        [0., 0., 0., ..., 4., 0., 1.]], dtype=float32)

In [42]:
movies_features.todense()

matrix([[0.00104167, 0.        , 0.        , ..., 0.        , 0.00104167,
         0.        ],
        [0.        , 0.00104167, 0.        , ..., 0.        , 0.00104167,
         0.        ],
        [0.        , 0.        , 0.00104167, ..., 0.        , 0.00104167,
         0.        ],
        ...,
        [0.        , 0.        , 0.        , ..., 0.        , 0.00104167,
         0.        ],
        [0.        , 0.        , 0.        , ..., 0.        , 0.00104167,
         0.        ],
        [0.        , 0.        , 0.        , ..., 0.        , 0.00104167,
         0.        ]], dtype=float32)

In [38]:
user_id_map, user_feature_map, item_id_map, item_feature_map = dataset.mapping()
item_id_map

{8: 0,
 18: 1,
 28: 2,
 30: 3,
 58: 4,
 77: 5,
 83: 6,
 97: 7,
 108: 8,
 111: 9,
 118: 10,
 143: 11,
 148: 12,
 175: 13,
 187: 14,
 189: 15,
 191: 16,
 197: 17,
 199: 18,
 223: 19,
 241: 20,
 252: 21,
 256: 22,
 257: 23,
 269: 24,
 270: 25,
 273: 26,
 275: 27,
 285: 28,
 290: 29,
 295: 30,
 299: 31,
 305: 32,
 311: 33,
 312: 34,
 313: 35,
 329: 36,
 330: 37,
 331: 38,
 334: 39,
 348: 40,
 353: 41,
 357: 42,
 361: 43,
 367: 44,
 393: 45,
 406: 46,
 413: 47,
 416: 48,
 424: 49,
 433: 50,
 442: 51,
 443: 52,
 457: 53,
 468: 54,
 473: 55,
 482: 56,
 483: 57,
 494: 58,
 501: 59,
 516: 60,
 528: 61,
 550: 62,
 551: 63,
 563: 64,
 564: 65,
 571: 66,
 607: 67,
 615: 68,
 629: 69,
 636: 70,
 658: 71,
 660: 72,
 662: 73,
 686: 74,
 692: 75,
 705: 76,
 708: 77,
 711: 78,
 720: 79,
 723: 80,
 746: 81,
 758: 82,
 759: 83,
 763: 84,
 788: 85,
 789: 86,
 798: 87,
 811: 88,
 818: 89,
 819: 90,
 831: 91,
 843: 92,
 851: 93,
 859: 94,
 862: 95,
 872: 96,
 886: 97,
 896: 98,
 897: 99,
 900: 100,
 908: 10

In [43]:
item_feature_map

{8: 0,
 18: 1,
 28: 2,
 30: 3,
 58: 4,
 77: 5,
 83: 6,
 97: 7,
 108: 8,
 111: 9,
 118: 10,
 143: 11,
 148: 12,
 175: 13,
 187: 14,
 189: 15,
 191: 16,
 197: 17,
 199: 18,
 223: 19,
 241: 20,
 252: 21,
 256: 22,
 257: 23,
 269: 24,
 270: 25,
 273: 26,
 275: 27,
 285: 28,
 290: 29,
 295: 30,
 299: 31,
 305: 32,
 311: 33,
 312: 34,
 313: 35,
 329: 36,
 330: 37,
 331: 38,
 334: 39,
 348: 40,
 353: 41,
 357: 42,
 361: 43,
 367: 44,
 393: 45,
 406: 46,
 413: 47,
 416: 48,
 424: 49,
 433: 50,
 442: 51,
 443: 52,
 457: 53,
 468: 54,
 473: 55,
 482: 56,
 483: 57,
 494: 58,
 501: 59,
 516: 60,
 528: 61,
 550: 62,
 551: 63,
 563: 64,
 564: 65,
 571: 66,
 607: 67,
 615: 68,
 629: 69,
 636: 70,
 658: 71,
 660: 72,
 662: 73,
 686: 74,
 692: 75,
 705: 76,
 708: 77,
 711: 78,
 720: 79,
 723: 80,
 746: 81,
 758: 82,
 759: 83,
 763: 84,
 788: 85,
 789: 86,
 798: 87,
 811: 88,
 818: 89,
 819: 90,
 831: 91,
 843: 92,
 851: 93,
 859: 94,
 862: 95,
 872: 96,
 886: 97,
 896: 98,
 897: 99,
 900: 100,
 908: 10

In [27]:
movies_features.todense()

matrix([[0.00104167, 0.        , 0.        , ..., 0.        , 0.00104167,
         0.        ],
        [0.        , 0.00104167, 0.        , ..., 0.        , 0.00104167,
         0.        ],
        [0.        , 0.        , 0.00104167, ..., 0.        , 0.00104167,
         0.        ],
        ...,
        [0.        , 0.        , 0.        , ..., 0.        , 0.00104167,
         0.        ],
        [0.        , 0.        , 0.        , ..., 0.        , 0.00104167,
         0.        ],
        [0.        , 0.        , 0.        , ..., 0.        , 0.00104167,
         0.        ]], dtype=float32)

In [3]:
import numpy as np

train, test = random_train_test_split(interactions, test_percentage=0.4,
                                              random_state=np.random.RandomState(7))

In [4]:
auc_train = auc_score(model, train, item_features=movies_features).mean()
print(auc_train)

0.58165187


In [5]:
auc_test = auc_score(model, test, item_features=movies_features).mean()
print(auc_test)

0.5659736


In [6]:
precision_train = precision_at_k(model, train, item_features=movies_features, k=10).mean()
print(precision_train)

0.45800868


In [7]:
precision_test = precision_at_k(model, test, item_features=movies_features, k=10).mean()
print(precision_test)

0.30865803


In [8]:
recall_train = recall_at_k(model, train, item_features=movies_features, k=10).mean()
print(recall_train)

0.005304988611989011


In [9]:
recall_test = recall_at_k(model, test, item_features=movies_features, k=10).mean()
print(recall_test)

0.005331419139533867


## Resampling

In [77]:
def _filter_data(self=LightFMRecommender()):
        """ To reduce size of sparse matrix during matrix factorization approach """
        min_movie_ratings = 29200 #0.885 quantile
        min_user_ratings = 779 #0.97 quantile

        df = self._read('final')
        filter_movies = (df['Movie_Id'].value_counts() > min_movie_ratings)
        filter_movies = filter_movies[filter_movies].index.tolist()

        filter_users = (df['Cust_Id'].value_counts() > min_user_ratings)
        filter_users = filter_users[filter_users].index.tolist()

        return df[(df['Movie_Id'].isin(filter_movies)) & (df['Cust_Id'].isin(filter_users))]

In [78]:
t = _filter_data()

In [79]:
t.shape

(12197359, 3)

In [38]:
t.Cust_Id.value_counts().max()

2032

In [58]:
raw_data.Movie_Id.value_counts().median()

561.0

In [75]:
raw_data.Cust_Id.value_counts().quantile([.95]) 

0.95    779.0
Name: Cust_Id, dtype: float64

In [76]:
raw_data.Movie_Id.value_counts().quantile([.95]) 

0.95    29199.6
Name: Movie_Id, dtype: float64

In [40]:
t.to_csv('sample_2.csv', index=False)